### ISSUE TITLE
Shift-Double-Click to add Marker

### ISSUE THREAD

**Issue by WardCunningham** [clemsos/wiki-plugin-map#11]
We have used the admittedly awkward shift-double-click to invoke specialized editing operations. I suggest we use it again now to add markers at specific locations after scrolling and zooming a map to find a location of interest.

This could be difficult to code because Leaflet would have to reveal the geo coordinate of the click AFTER our own javascript handler had examined the event to determine that the shift key was held down. Can it do this?

Scrolling and zooming no longer modify the page contents. This is good. A reader who explores will find the map returned to its proper placement next time the page is recalled. But we now need a way for authors to position maps and identify points of interest. This would be that.

Shift-double-click would add the marker with the label `click` and then post the change to the server. Better marker labels could be provided by editing the markup the normal way.

**Comment by WardCunningham** [comment]
I just got something working that adds markers. Will push to new pull request before bed. Might have to fine tune it in the morning.

**Comment by clemsos** [comment]
Great ! I really like the idea to allow user to directly select points or draw lines on the map - like explained in #14 . One important thing is that we need to think of an interaction to modify/move markers once they have been added

**Comment by WardCunningham** [comment]
The `click` labels looked stupid. Shift-double-clicks now adds markers with no label at all.  This alone will distinguish them from markers that have been lovingly marked up by an author.
![screen shot 2016-07-07 at 12 17 55 am](https://cloud.githubusercontent.com/assets/12127/16645381/6c33f890-43d8-11e6-8159-6502c4f71fbe.png)

**Comment by WardCunningham** [comment]
8f042a0 rounds coordinates to seven digits for a precision of one centimeter.

![image](https://cloud.githubusercontent.com/assets/12127/16655932/70332662-4411-11e6-838c-d6b7011b53ba.png)

Here are more bridges in New York City.

![image](https://cloud.githubusercontent.com/assets/12127/16655986/add76b9a-4411-11e6-82cc-f1c0708d5d66.png)

**Comment by WardCunningham** [comment]
There is a wiki server turn-around with each shift-double-click plus whatever leaflet does. I've been testing this over the long path to my server in Singapore.

```
--- asia.wiki.org ping statistics ---
14 packets transmitted, 14 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 223.293/342.527/527.410/94.709 ms
```
I find it to be robust but not 100% reliable. By this I mean that it can fail but doesn't do damage when it does. The marker will show before the action appears in the journal. The marker appears at the beginning of the post while the journal updates on its completion. We've seen fast edits (like computer fast) lose client-server sync but haven't seen it happen here.

When it fails it becomes insensitive to shift-double-clicks. Opening and closing the markup editor redraws the map upon which it becomes sensitive again. It is more likely to lose sensitivity after placing many markers. I've also seen it insensitive to the first shift-double-click, a condition that clears itself. I've also seen it interpret a shift-double-click as a zoom command. 

Here is how chrome's timeline sees the operation. This looks pretty much as expected with the ajax post ending this part of the story. The marker and shadow paint in a subsequent 100 msec and the journal post reply paints 200 msec after that.

![image](https://cloud.githubusercontent.com/assets/12127/16657272/c4059fea-4416-11e6-98ee-4e9c7569dbb4.png)

**Comment by WardCunningham** [comment]
I'll close this issue with #15 as is. I'm happy to see it reopened after we have more experience making maps and understanding workflows where clicking and text editing are combined.

**Comment by WardCunningham** [comment]
A centimeter might be too much precision. How big is a pixel at the most detailed available tiles?
