### ISSUE TITLE
Accept Integers as Coordinates

### ISSUE THREAD

**Issue by WardCunningham** [clemsos/wiki-plugin-map#13]
I should be able to markup confluences without adding decimal points to the lat and lon.

```
First Visits by Ward [http://c2.com/ward/confluence/ site]
46, 122 Wind River
47, 122 Bagby
```
The current rules require the dot but not fraction digits. Consider carefully how regex match when most punctuation is optional.

**Comment by opn** [comment]
How do people usually get of find a coordinate manually? Probably from Google Maps. So let's make it easy. You can see from the links copied - either from the url bar or from the share feature - that they contain the decimal lat and long as well as zoom:
- [https://www.google.com/maps/place/Finsbury+Park/@51.5687115,-0.1048946,17z/data=!3m1!4b1!4m5!3m4!1s0x48761b854518c3ff:0x3b1ea39b68070798!8m2!3d51.5687115!4d-0.1027059](https://www.google.com/maps/place/Finsbury+Park/@51.5687115,-0.1048946,....)
- [https://www.google.com/maps/place/Lee+Terrace,+London+SE3+9TA,+UK/@51.4645416,0.0059226,17z/data=!3m1!4b1!4m5!3m4!1s0x47d8a9d0fae98fb5:0x469bccdf3387dcb5!8m2!3d51.4645933!4d0.0081281](https://www.google.com/maps/place/Lee+Terrace,+London+SE3+9TA,+UK/@51.4645416,0.0059226,17z/data=!3m1!4b1!4m5!3m4!1s0x47d8a9d0fae98fb5:0x469bccdf3387dcb5!8m2!3d51.4645933!4d0.0081281)

So the first link contains - 51.5687115,-0.1048946,17z - so we definitely want to be able to just add these numbers. In fact why not allow people to enter the zoom level for a pin / each pin. And why not allow people to just copy and paste the whole url and allow the map plugin to parse it / clean out the junk?

**Comment by WardCunningham** [comment]
I tried the second case.

Here I clicked the link you provided.

![image](https://cloud.githubusercontent.com/assets/12127/16640085/0f99afae-43aa-11e6-84e3-a0ac77ba3cbd.png)

Here I pasted the numbers into a line of markup.

![image](https://cloud.githubusercontent.com/assets/12127/16640101/2b4f91c8-43aa-11e6-8438-b2079d1db70b.png)

These parsed correctly because the numbers did have the expected decimal points. 

I can't explain why the markers aren't in identical positions. 

I do notice some suspicious similarities in the tiles. Both show a stray road segment on the northwest corner of the block. Have you been to this location? Is there a short stub of a road at a shallow angle to Lawn Terrace with apex at the train station?

**Comment by WardCunningham** [comment]
Commit 3bf81e6 accepts integers without decimal points. This was tricky as explained in #8.

**Comment by paul90** [comment]
> I can't explain why the markers aren't in identical positions.

Those two points are within 100m of each other - this is a few 1/1000 of a degree difference. 

> Is there a short stub of a road at a shallow angle to Lawn Terrace with apex at the train station?

Only virtually been to that location, and yes there is a road there Independents Road - providing access to Blackheath Hospital. *Also shows on A-Z*
