### ISSUE TITLE
Write help section

### ISSUE THREAD

**Issue by clemsos** [clemsos/wiki-plugin-map#4]

**Comment by WardCunningham** [comment]
It is customary to document plugins in an about-map-plugin page held in the pages subdirectory. The about page should have a brief description, an example, external link to source code, and explanation of the markup. Additional pages suitably named to be unambiguous (more-about-map-plugin).

One can easily edit about pages by launching wiki from within the plugin repo.

```
wiki -d . -p 3030
```
Be careful not to checkin unwanted pages or sitemaps made while editing.
