### ISSUE TITLE
Add map aggregation

### ISSUE THREAD

**Issue by opn** [clemsos/wiki-plugin-map#6]
Define a data-structure for maps to reveal in the same way that the Method and Graph plugins reveal data in the lineup that other plugins can respond to.

We should add the same ability that the wiki-graph-plugin - https://github.com/WardCunningham/wiki-plugin-graph so that the wiki-map-plugin is able to display a map from data not just inside it's own markup but taken from other wiki-map-plugin present in the lineup, or at remote sites specified in the markup.

See http://bio.commons.world/bio-commons-camp.html

**Comment by clemsos** [comment]
@WardCunningham explains in #7 how we can aggregate info using the `markerData()` and `markerGeo()` commands.

However, it may be better if aggregating data on the map is only optional. Now, the `candidates` that exposes data are automatically added to map.

For instance, I have two maps here, one with one marker, the other with three markers.

![tooltip_151](https://cloud.githubusercontent.com/assets/743246/16491281/a61fddee-3edd-11e6-9d17-cc00a5479ac5.png)

But on the second map, the 4 markers are shown.

![selection_152](https://cloud.githubusercontent.com/assets/743246/16491350/e6a386ae-3edd-11e6-85a3-98d91a9818c9.png)

I don't think it should be expected. Maybe we can have a word or instruction that will trigger aggregation of the markers on the map ?

**Comment by WardCunningham** [comment]
I would not expect imported markers to affect the map bounds unless they were the only position information available.

We could write __LINEUP__ when we wanted to include markers found in the lineup. Perhaps if we asked for them explicitly we would expect them to influence bounds.

If this seems logical, the candidate search could move to the parse function triggered by /^LINEUP$/

I would like to write __NEIGHBORS__ and have all markers in the neighborhood added to the map. I haven't thought through all possibilities for what should or shouldn't be included computing bounds. Perhaps we could say __BOUNDS__ where in the sequence of accumulating markers we want to compute bounds. If left out, bounds would be computed for all markers.
